---
- name: Add configure command
  set_fact:
    vyos_config:
      '{{ [ "configure" ] + vyos_config + [ { "command": "commit-confirm 10",
      "prompt": [
      "Proceed \? \[Y/n\]"
      ],
      "answer": "y" },
      "exit" ] }}'
- name: Apply config
  vyos.vyos.vyos_command:
    commands: "{{ vyos_config }}"
    retries: 0
    match: any
  when:
    - vyos_config is defined

- name: confirm commit
  vyos.vyos.vyos_command:
    commands:
      - configure
      - confirm
      - exit
