---
- name: Pull container images
  vyos.vyos.vyos_command:
    commands:
      - "update container image {{ item.name }}"
  loop: "{{ containers }}"

- name: Start containers
  vyos.vyos.vyos_command:
    commands:
      - "restart container {{ item.name }}"
  when: item.start is undefined or item.start == true
  loop: "{{ containers }}"
