---
- name: Template container config
  set_fact:
    vyos_config: "{{ vyos_config + lookup('ansible.builtin.template', item).split('\n')[:-1] }}"
  loop:
    - 'container_networks.j2'
    - 'containers.j2'

