---
- name: Init vyos_config
  set_fact:
    vyos_config: []
  tags:
    - never
    - dry-run

- name: Template config
  set_fact:
    vyos_config: "{{ vyos_config + lookup('ansible.builtin.template', item).split('\n')[:-1] }}"
  loop: "{{ lookup('fileglob', 'templates/*.j2', wantlist=True) }}"
  tags:
    - never
    - dry-run

- name: Print config
  ansible.builtin.debug:
    msg: "{{ vyos_config }}"
  tags:
    - never
    - dry-run
