---
- name: Template firewall config
  set_fact:
    vyos_config: "{{ vyos_config + lookup('ansible.builtin.template', item).split('\n')[:-1] }}"
  loop:
    - 'firewall_options.j2'
    - 'firewall_groups.j2'
    - 'firewall_zones.j2'
    - 'firewall_flowtables.j2'
    - 'firewall_rules.j2'

