---
- name: Define static routes
  vyos.vyos.vyos_config:
    src: static_routes.j2
    match: none
  when:
    - static_routes is defined

- name: Define BGP
  vyos.vyos.vyos_config:
    src: bgp.j2
    match: none
  when:
    - bgp is defined
