---
- name: Template services config
  set_fact:
    vyos_config: "{{ vyos_config + lookup('ansible.builtin.template', item).split('\n')[:-1] }}"
  loop:
    - 'dns.j2'
    - 'ddns.j2'
    - 'ntp.j2'
    - 'ssh.j2'
    - 'mdns.j2'
    - 'cron.j2'

